### ISSUE TITLE
装上就报错

### ISSUE THREAD

**Issue by Vulpes1agopus** [ThinkingStudios/MaLiLib-Forge#17]
[097月2023 00:55:36.799] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Vulpes1agous, --version, 1.20.1-Forge_47.0.3, --gameDir, D:\minecraft\.minecraft\versions\1.20.1-Forge_47.0.3, --assetsDir, D:\minecraft\.minecraft\assets, --assetIndex, 5, --uuid, 3faa3476d7ab479ea7046ac71e271ac2, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --quickPlayPath, ${quickPlayPath}, --launchTarget, forgeclient, --fml.forgeVersion, 47.0.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[097月2023 00:55:36.815] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[097月2023 00:55:37.475] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[097月2023 00:55:37.476] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/D:/minecraft/.minecraft/versions/1.20.1-Forge_47.0.3/mods/preview_OptiFine_1.20.1_HD_U_I5_pre9.jar%23172!/
[097月2023 00:55:37.485] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: D:\minecraft\.minecraft\versions\1.20.1-Forge_47.0.3\mods\preview_OptiFine_1.20.1_HD_U_I5_pre9.jar
[097月2023 00:55:37.488] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[097月2023 00:55:37.531] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/minecraft/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23149!/ Service=ModLauncher Env=CLIENT
[097月2023 00:55:37.537] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[097月2023 00:55:37.947] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.0.3\fmlcore-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 00:55:37.994] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.0.3\javafmllanguage-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 00:55:38.021] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.0.3\lowcodelanguage-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 00:55:38.049] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.0.3\mclanguage-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 00:55:38.157] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 3 dependencies adding them to mods collection
[097月2023 00:55:38.512] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[097月2023 00:55:38.517] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 411
[097月2023 00:55:39.024] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[097月2023 00:55:39.376] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[097月2023 00:55:39.384] [main/ERROR] [mixin/]: Mixin config mixins.baritone.json does not specify "minVersion" property
[097月2023 00:55:39.483] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [baritone.launch.BaritoneMixinConnector]
[097月2023 00:55:39.484] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-Forge_47.0.3, --gameDir, D:\minecraft\.minecraft\versions\1.20.1-Forge_47.0.3, --assetsDir, D:\minecraft\.minecraft\assets, --uuid, 3faa3476d7ab479ea7046ac71e271ac2, --username, Vulpes1agous, --assetIndex, 5, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --quickPlayPath, ${quickPlayPath}]
[097月2023 00:55:40.354] [main/WARN] [IMixinConfigPlugin/]: Inventory Profiles Next: Doing our own dependency resolving! Because Forge is being Forge....: https://github.com/MinecraftForge/MinecraftForge/issues/9088

**Comment by Vulpes1agopus** [comment]
我把高清修复删了也这样
[097月2023 01:06:27.657] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Vulpes1agous, --version, 1.20.1-Forge_47.0.3, --gameDir, D:\minecraft\.minecraft\versions\1.20.1-Forge_47.0.3, --assetsDir, D:\minecraft\.minecraft\assets, --assetIndex, 5, --uuid, 3faa3476d7ab479ea7046ac71e271ac2, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --quickPlayPath, ${quickPlayPath}, --launchTarget, forgeclient, --fml.forgeVersion, 47.0.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[097月2023 01:06:27.661] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[097月2023 01:06:27.932] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/minecraft/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23149!/ Service=ModLauncher Env=CLIENT
[097月2023 01:06:28.298] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.0.3\fmlcore-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 01:06:28.305] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.0.3\javafmllanguage-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 01:06:28.311] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.0.3\lowcodelanguage-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 01:06:28.318] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file D:\minecraft\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.0.3\mclanguage-1.20.1-47.0.3.jar is missing mods.toml file
[097月2023 01:06:28.424] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 3 dependencies adding them to mods collection
[097月2023 01:06:29.495] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[097月2023 01:06:29.508] [main/ERROR] [mixin/]: Mixin config mixins.baritone.json does not specify "minVersion" property
[097月2023 01:06:29.593] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [baritone.launch.BaritoneMixinConnector]
[097月2023 01:06:29.594] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-Forge_47.0.3, --gameDir, D:\minecraft\.minecraft\versions\1.20.1-Forge_47.0.3, --assetsDir, D:\minecraft\.minecraft\assets, --uuid, 3faa3476d7ab479ea7046ac71e271ac2, --username, Vulpes1agous, --assetIndex, 5, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --quickPlayPath, ${quickPlayPath}]
[097月2023 01:06:30.223] [main/WARN] [IMixinConfigPlugin/]: Inventory Profiles Next: Doing our own dependency resolving! Because Forge is being Forge....: https://github.com/MinecraftForge/MinecraftForge/issues/9088
[097月2023 01:06:33.877] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 188 Datafixer optimizations took 100 milliseconds
[097月2023 01:06:35.579] [Client Shutdown Thread/ERROR] [net.minecraft.client.main.Main/]: Caught previously unhandled exception :
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main$2.run(Main.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23188!/:?]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onRenderTooltip(Lnet/minecraft/client/gui/GuiGraphics;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in malilib.mixins.json:MixinHandledScreen failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MaFgLib-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	... 30 more

**Comment by TexBlock** [comment]
单独安装时无法复现，请提供完整的模组列表

**Comment by Kasualix** [comment]
[换了个实现](https://github.com/ThinkingStudios/MaLiLib-Forge/suites/14317732782/artifacts/805492599)，再注入失败就是别的模组过于invasive的锅了

**Comment by TexBlock** [comment]
FIXED
