### ISSUE TITLE
texture bug

### ISSUE THREAD

**Issue by Mccandycube6623** [ThinkingStudios/MaLiLib-Forge#29]
按钮显示为黑紫色
forge1.18.2，mafglib0.1.7
可能和这个有关
[2412月2023 10:50:14.428] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: mafglib:textures/gui/gui_widgets.png
java.io.FileNotFoundException: mafglib:textures/gui/gui_widgets.png
	at net.minecraft.server.packs.resources.MultiPackResourceManager.m_142591_(MultiPackResourceManager.java:50) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142591_(ReloadableResourceManager.java:49) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureImage.m_118155_(SimpleTexture.java:81) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6335_(SimpleTexture.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.m_6704_(SimpleTexture.java:28) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118515_(TextureManager.java:95) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118495_(TextureManager.java:66) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.renderer.texture.TextureManager.m_118506_(TextureManager.java:118) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_157179_(RenderSystem.java:1216) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.m_157456_(RenderSystem.java:1209) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at fi.dy.masa.malilib.render.RenderUtils.bindTexture(RenderUtils.java:78) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.bindTexture(WidgetBase.java:157) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.widgets.WidgetIcon.render(WidgetIcon.java:20) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.widgets.WidgetSearchBar.render(WidgetSearchBar.java:126) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.widgets.WidgetSearchBarConfigs.render(WidgetSearchBarConfigs.java:88) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.drawContents(WidgetListBase.java:387) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.GuiListBase.drawContents(GuiListBase.java:178) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at fi.dy.masa.malilib.gui.GuiBase.m_6305_(GuiBase.java:178) ~[MaFgLib-0.1.7-mc1.18.2.jar%23176!/:0.1.7-mc1.18.2]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.2.10-universal.jar%23271!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.2.10-universal.jar%23271!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23266!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.10.jar%2352!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]

**Comment by TexBlock** [comment]
fixed in 0.1.8-mc1.18.2
