### ISSUE TITLE
Forgematica does not recognize MaFgLib as a MaLiLib port

### ISSUE THREAD

**Issue by AaronPesch** [ThinkingStudios/MaLiLib-Forge#35]
Basically what is written above. When launching the modpack including MaFgLib and Forgematica it states in the crash-log, that MaLiLib is required.
Here's the log if needed: https://paste.ee/p/Yv09x

**Comment by AsheX1** [comment]
you are using the wrong version mate [14:29:38] [main/INFO]: Found mod file MaFgLib-0.1.9-mc1.19.2.jar of type MOD with provider {mods folder locator at C:\Users\vemni\curseforge\minecraft\Instances\esca Modpack\mods}

that is the 1.19.2 version on a 1.20.1 minecraft verion i take not gone keep reading in the log just get the last jar from #38 
that one has the mods.toml fixed

**Comment by AaronPesch** [comment]
Are you sure? It states on the curseforge website that it is a combined version for 1.20 and 1.19 so I just went with it. I also though that this would maybe cause some issues so I tried the specific 1.20 port but it threw the same error back then. I'm gonna check out the version you sent real quick

**Comment by AaronPesch** [comment]
> that is the 1.19.2 version on a 1.20.1 minecraft verion i take not gone keep reading in the log just get the last jar from #38 that one has the mods.toml fixed

I tried this but the client/game does not recognize the mod (mod never found in logs), which totally makes sense since you removed the modID which corresponded to MaLiLib so other mods recognize it. 
Can you run other mods as well, that need MaFgLib?

Edit: I tried playing around with it and for some reason got a Minecraft Crash: Exit Code 1. No idea why since I basically havn't changed a thing

**Comment by AsheX1** [comment]
can i see the new log?
and a full screensshot of the mods folder

**Comment by AsheX1** [comment]
> > that is the 1.19.2 version on a 1.20.1 minecraft verion i take not gone keep reading in the log just get the last jar from #38 that one has the mods.toml fixed
> 
> I tried this but the client/game does not recognize the mod (mod never found in logs), which totally makes sense since you removed the modID which corresponded to MaLiLib so other mods recognize it. Can you run other mods as well, that need MaFgLib?
> 
> Edit: I tried playing around with it and for some reason got a Minecraft Crash: Exit Code 1. No idea why since I basically havn't changed a thing

here is second thing i just check the old log again you are also using an outdated forgematica version
here is the link to the last version https://modrinth.com/mod/forgematica/version/0.1.2-mc1.20.1

and on top of that there is no combined version of MaFgLib jar you download the worng one

still wanne see a screen shot of all the mods in the mods folder and log if its still crashing

**Comment by AaronPesch** [comment]
> > > that is the 1.19.2 version on a 1.20.1 minecraft verion i take not gone keep reading in the log just get the last jar from #38 that one has the mods.toml fixed
> > 
> > 
> > I tried this but the client/game does not recognize the mod (mod never found in logs), which totally makes sense since you removed the modID which corresponded to MaLiLib so other mods recognize it. Can you run other mods as well, that need MaFgLib?
> > Edit: I tried playing around with it and for some reason got a Minecraft Crash: Exit Code 1. No idea why since I basically havn't changed a thing
 
Yeah was playing around with them, tried the newest version (beta-release) and the newest official release version (the one you saw). 

I launched the pack with the newest Forgematica version and your MaFgLib version and get Exit-Code: 1 with the following log: https://paste.ee/p/BR8cm

**Comment by AsheX1** [comment]
> > > > that is the 1.19.2 version on a 1.20.1 minecraft verion i take not gone keep reading in the log just get the last jar from #38 that one has the mods.toml fixed
> > > 
> > > 
> > > I tried this but the client/game does not recognize the mod (mod never found in logs), which totally makes sense since you removed the modID which corresponded to MaLiLib so other mods recognize it. Can you run other mods as well, that need MaFgLib?
> > > Edit: I tried playing around with it and for some reason got a Minecraft Crash: Exit Code 1. No idea why since I basically havn't changed a thing
> 
> Yeah was playing around with them, tried the newest version (beta-release) and the newest official release version (the one you saw).
> 
> I launched the pack with the newest Forgematica version and your MaFgLib version and get Exit-Code: 1 with the following log: https://paste.ee/p/BR8cm

thats not the full log..... can you just put all mods in a zip file and upload it to google driver or onedrive and give me the link as you are not really giving any usefull info

PUT ALL THE  MODS IN A ZIP AND UPLOAD THEM so i can check it my self

**Comment by AaronPesch** [comment]
Ahh sorry, i forgot. Here's the modpack https://drive.google.com/drive/folders/1dwa0MDoz62TLjBTqSXGg4n992o2lwvUx?usp=drive_link

**Comment by AsheX1** [comment]
ALSO YOU NEVER DELETED THE OLD Mafglib!!!!!!!!
[18:53:57] [main/INFO]: Found mod file MaFgLib-0.1.9-mc1.19.2.jar of type MOD with provider {mods folder locator at C:\Users\vemni\curseforge\minecraft\Instances\esca Modpack\mods}

upload all the mods in a zip so i can check it my self as im 100% sure you are fucking up somewhere 

i put my own pack togeter and im at 206 mods and i can use forge and neoforge  on 1.20.1 and i have everything working

just give me all the mods in a zip so can create a profile my self to check what is wrong

**Comment by AsheX1** [comment]
as far as i can see its not loading the new mafglib as you still have the old 1.19.2 in the mods folder

**Comment by AaronPesch** [comment]
> as far as i can see its not loading the new mafglib as you still have the old 1.19.2 in the mods folder

wow that was actually it. Didn't check the folder for old versions. Thanks a lot mate!!!

**Comment by AaronPesch** [comment]
Wow that was actually it, didn't check for old versions in the folder. Thanks a lot mate!!!

**Comment by JAYTRONYX** [comment]
[02:10:53] [main/INFO]: ModLauncher running: args [--username, [CENSURADO_USERNAME], --version, ForgeOptiFine 1.18.2, --gameDir, C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft, --assetsDir, C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, [CENSURADO_UUID], --accessToken, [CENSURADO_TOKEN], --clientId, null, --xuid, null, --userType, mojang, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.26, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[02:10:53] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.15 by Microsoft
[02:10:53] [main/INFO]: OptiFineTransformationService.onLoad
[02:10:53] [main/INFO]: OptiFine ZIP file URL: union:/C:/Users/[CENSURADO_USER]/AppData/Roaming/.minecraft/mods/OptiFine-1.18.2_HD_U_H9_pre3.jar%2356!/
[02:10:54] [main/INFO]: OptiFine ZIP file: C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods\OptiFine-1.18.2_HD_U_H9_pre3.jar
[02:10:54] [main/INFO]: Target.PRE_CLASS is available
[02:10:54] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/[CENSURADO_USER]/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[02:10:54] [main/INFO]: OptiFineTransformationService.initialize
[02:10:54] [main/INFO]: Found mod file [1.18.2] SecurityCraft v1.9.8.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file AI-Improvements-1.18.2-0.5.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file appleskin-forge-mc1.18.2-2.5.1.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file artifacts-1.18.2-4.2.3.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file balm-3.2.6.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file BoccHUD-0.1.7-mc1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file cave_dweller-1.18.2-1.6.4.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file citadel-1.11.3-1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file comforts-forge-1.18.2-5.0.0.6.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file corpse-1.18.2-1.0.1.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file CreativeCore_FORGE_v2.6.17_mc1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file creeperoverhaul-1.3.1-forge.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file curios-forge-1.18.2-5.0.9.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file DungeonsArise-1.18.2-2.1.52-release.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file EasierSleeping-1.18.2-2.1.3.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file expandability-6.0.0.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file FallingTree-1.18.2-3.5.5.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file freecam-forge-1.3.5+mc1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file geckolib-forge-1.18-3.0.57.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file goblintraders-1.8.0-1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file Jade-1.18.2-forge-5.3.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file jei-1.18.2-forge-10.2.1.1005.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file journeymap-1.18.2-5.9.7p1-forge.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file MiniHUD-Extra-0.2.0-mc1.18.2-forge.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file PlayerRevive_FORGE_v2.0.13_mc1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file portablemobs-1.2.0-forge-mc1.18.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file sophisticatedbackpacks-1.18.2-3.20.2.1036.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file sophisticatedcore-1.18.2-0.6.4.586.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file starlight-1.0.2+forge.546ae87.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file supermartijn642corelib-1.1.16-forge-mc1.18.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file TerraBlender-forge-1.18.2-1.2.0.126.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file tl_skin_cape_forge_1.18_1.18.2-1.38.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file torchmaster-18.2.1.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file trashslot-forge-1.18.2-11.0.3.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/INFO]: Found mod file waystones-forge-1.18.2-10.2.2.jar of type MOD with provider {mods folder locator at C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\mods}
[02:10:54] [main/WARN]: Mod file C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.26\fmlcore-1.18.2-40.2.26.jar is missing mods.toml file
[02:10:54] [main/WARN]: Mod file C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.26\javafmllanguage-1.18.2-40.2.26.jar is missing mods.toml file
[02:10:54] [main/WARN]: Mod file C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.26\lowcodelanguage-1.18.2-40.2.26.jar is missing mods.toml file
[02:10:54] [main/WARN]: Mod file C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.26\mclanguage-1.18.2-40.2.26.jar is missing mods.toml file
[02:10:54] [main/INFO]: Found mod file fmlcore-1.18.2-40.2.26.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@[CENSURADO]
[02:10:54] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.2.26.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@[CENSURADO]
[02:10:54] [main/INFO]: Found mod file lowcodelanguage-1.18.2-40.2.26.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@[CENSURADO]
[02:10:54] [main/INFO]: Found mod file mclanguage-1.18.2-40.2.26.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@[CENSURADO]
[02:10:54] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@[CENSURADO]
[02:10:54] [main/INFO]: Found mod file forge-1.18.2-40.2.26-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@[CENSURADO]
[02:10:55] [main/INFO]: Found 1 dependencies adding them to mods collection
[02:10:55] [main/INFO]: Found mod file cloth-config-forge-6.5.102.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@[CENSURADO]
[02:10:55] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'architectury', Requested by: 'minihudextra', Expected range: '[3.9.66,)', Actual version: '[MISSING]'
	Mod ID: 'mafglib', Requested by: 'bocchud', Expected range: '*', Actual version: '[MISSING]'
[02:10:55] [main/INFO]: OptiFineTransformationService.transformers
[02:10:55] [main/INFO]: Targets: 360
[02:10:56] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[02:10:57] [main/INFO]: Compatibility level set to JAVA_17
[02:10:58] [main/INFO]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[02:10:58] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[02:10:58] [main/INFO]: Launching target 'forgeclient' with arguments [--version, ForgeOptiFine 1.18.2, --gameDir, C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft, --assetsDir, C:\Users\[CENSURADO_USER]\AppData\Roaming\.minecraft\assets, --uuid, [CENSURADO_UUID], --username, [CENSURADO_USERNAME], --assetIndex, 1.18, --accessToken, [CENSURADO_TOKEN], --clientId, null, --xuid, null, --userType, mojang, --versionType, modified, --width, 925, --height, 530]
[02:10:58] [main/WARN]: Reference map 'creativecore.mixins.refmap.json' for creativecore.mixins.json could not be read. If this is a development environment you can ignore this message
[02:10:59] [main/WARN]: Error loading class: me/cominixo/betterf3/modules/TargetModule (java.lang.ClassNotFoundException: me.cominixo.betterf3.modules.TargetModule)
[02:10:59] [main/WARN]: @Mixin target me.cominixo.betterf3.modules.TargetModule was not found securitycraft.mixins.json:f3.BetterF3TargetModuleMixin
[02:10:59] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/HandRenderer (java.lang.ClassNotFoundException: net.coderbot.iris.pipeline.HandRenderer)
[02:10:59] [main/WARN]: Error loading class: net/coderbot/iris/pipeline/ShadowRenderer (java.lang.ClassNotFoundException: net.coderbot.iris.pipeline.ShadowRenderer)
[02:11:03] [main/WARN]: Failed to add PDH Counter: \Paging File(_Total)\% Usage, Error code: 0xC0000BB8
[02:11:03] [main/WARN]: Failed to add counter for PDH counter: \Paging File(_Total)\% Usage
[02:11:03] [main/WARN]: Disabling further attempts to query Paging File.
[02:11:06] [main/WARN]: COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[02:11:08] [main/WARN]: Error loading class: fi/dy/masa/malilib/config/options/ConfigBooleanHotkeyed (java.lang.ClassNotFoundException: fi.dy.masa.malilib.config.options.ConfigBooleanHotkeyed)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.26/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at TRANSFORMER/net.optifine/net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at TRANSFORMER/net.optifine/net.optifine.reflect.Reflector.<clinit>(Reflector.java:522)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.m_127526_(CrashReport.java:173)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.m_127529_(CrashReport.java:343)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:137)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: fi.dy.masa.malilib.config.options.ConfigBooleanHotkeyed
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 34 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (14 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1
flush now
flush now
COMO SOLUSIONO LA INCOMPATIBILIDAD DE mafglib Y  malilib
