### ISSUE TITLE
MaFgLib mixin config issue

### ISSUE THREAD

**Issue by Obscrts** [ThinkingStudios/MaLiLib-Forge#46]
```[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Pre-Start Tasks Complete
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Java Runtime Validated
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Assets Validated
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Libraries Validated
[FTB APP][INFO] Validate client
[FTB APP][INFO] Client Validated
[FTB APP][INFO] Extract natives
[FTB APP][INFO] Natives Extracted
[FTB APP][INFO] Prepare process
[FTB APP][INFO] Process Prepared
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
[Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
[Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
2024-06-30 21:46:20,380 main WARN Advanced terminal features are not available in this environment
[21:46:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Obscrts, --version, 1.16.5-forge-36.2.26, --gameDir, C:\Users\Cedric\AppData\Local\.ftba\instances\ftb ultimate anniversary edition, --assetsDir, C:\Users\Cedric\AppData\Local\.ftba\bin\assets, --assetIndex, 1.16, --uuid, 91a2f910-f049-49b2-b804-16052522174a, --accessToken, ????????, --userType, msa, --versionType, release, --width, 2560, --height, 1440, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.26, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[21:46:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_312 by Temurin
[21:46:20] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[21:46:20] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/Cedric/AppData/Local/.ftba/bin/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[21:46:21] [main/INFO] [STDOUT/]: [net.creeperhost.traylauncher.ModLocatorHack:<init>:32]: Initializing launcher communication
[21:46:21] [ForkJoinPool.commonPool-worker-25/INFO] [STDOUT/]: [net.creeperhost.traylauncher.LauncherCommunicator:lambda$connect$0:77]: Connected to launcher
[21:46:24] [main/ERROR] [mixin/]: Mixin config bcc.mixins.json does not specify "minVersion" property
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mafglib.forge.mixins.json
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[21:46:24] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1290)
```

**Comment by TexBlock** [comment]
fixed
